[package]
name = "edhoc"
version = "0.1.0"
authors = ["Ask Sejsbo <asse@itu.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/S3j5b0/edhoc"
documentation  = "https://github.com/S3j5b0/edhoc"
description = "Experimental EDHOC implementation with fourth optional message"



[lib]
doctest = false

[dependencies]
serde = { version = "1.0.97", default-features = false, features = ["derive", "alloc"] }
serde_cbor = { version = "0.11.2", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11.1", default-features = false, features = ["alloc"] }
x25519-dalek-ng = { version = "1.1.1", default-features = false, features = ["u32_backend"] }
rand_core = "0.6.2"
sha2 = { version = "0.8.0", default-features = false }
aes = "0.7.5"
ccm = "0.4.4"
hkdf = "0.8.0"
digest = "0.8.1"



[features]
default = ["std"]
std = [
    "serde/std",
    "serde_cbor/std",
    "serde_bytes/std",
    "x25519-dalek-ng/std",
    "sha2/std",
    "ccm/std",
    "hkdf/std",
    "digest/std",
]
# This disables replay protection, which is necessary for benchmarking
no_replay = []

